# .github/workflows/ci.yml  (en repos consumidores)
name: CI (calls org reusable)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  call-org:
    permissions:
      contents: read
    uses: gperezusil/repo-template/.github/workflows/template-ci.yml@main
    with:
      image_name: devsecops-app
      acr_name: mibanco.azurecr.io
      deploy: true
      azure_oidc: true
      staging_url: https://staging.myapp.internal
    secrets:
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}